# Generated by Django 3.2 on 2021-05-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('day', models.CharField(max_length=250)),
                ('time', models.TimeField(default='14:00')),
                ('description', models.TextField(max_length=250)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceapp.registrationform')),
            ],
        ),
    ]
